// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGNq-ueeb_4N8hhYyOMND2le7nyk30gBQ',
    appId: '1:578682965712:web:bcf57981baf4f5070058d5',
    messagingSenderId: '578682965712',
    projectId: 'moovera-760e7',
    authDomain: 'moovera-760e7.firebaseapp.com',
    storageBucket: 'moovera-760e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2BiqW_0VeQk-zGsYSFEHUn5y8y04Ps60',
    appId: '1:578682965712:android:ae1a2b70087fffa40058d5',
    messagingSenderId: '578682965712',
    projectId: 'moovera-760e7',
    storageBucket: 'moovera-760e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOr7ACHZDf_Q6TznKIkeMx0dBx7f2YNNE',
    appId: '1:578682965712:ios:b27e126b79905d460058d5',
    messagingSenderId: '578682965712',
    projectId: 'moovera-760e7',
    storageBucket: 'moovera-760e7.appspot.com',
    androidClientId: '578682965712-1ba697h1u8qd0p0cq3vftpg9p100e4hn.apps.googleusercontent.com',
    iosClientId: '578682965712-id1nfe85is07e0vk9pseg5ue4i52kua9.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieLogin',
  );
}
